/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminProduct;

import GUI.AdminOrder.AddOrder;
import GUI.AdminCustomer.AddCustomer;
import GUI.AdminHome.AdminHome;
import GUI.LoginPage;
import assignment.Customers.CustomerManager;
import assignment.Orders.Cart;
import assignment.Orders.CartManager;
import assignment.Orders.Order;
import assignment.Orders.OrderManager;
import assignment.Products.Product;
import assignment.Products.ProductManager;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class EditProduct extends javax.swing.JFrame {

    ArrayList<Product> productList = new ArrayList<>();
    DecimalFormat df = new DecimalFormat("#.##");

    /**
     * Creates new form EditProduct
     */
    public EditProduct() {
        initComponents();
        this.setLocationRelativeTo(null);
        addRow2JTable();
        sortTable();
    }

    public void addRow2JTable() {
        DefaultTableModel model = (DefaultTableModel) productTbl.getModel();
        ProductManager pManager = new ProductManager();
        try {
            productList = pManager.read();
            Object rowData[] = new Object[6];
            model.setRowCount(0);
            for (int i = 0; i < productList.size(); i++) {
                rowData[0] = productList.get(i).getProductID();
                rowData[1] = productList.get(i).getProductName();
                rowData[2] = productList.get(i).getCategory();
                rowData[3] = productList.get(i).getType();
                rowData[4] = productList.get(i).getPrice();
                rowData[5] = productList.get(i).getStock();
                model.addRow(rowData);

            }

        } catch (IOException e) {
            System.out.println("Error");
        }

    }

    public void displayProDetails() {

        DefaultTableModel model = (DefaultTableModel) productTbl.getModel();

        int selectedRow = productTbl.convertRowIndexToModel(productTbl.getSelectedRow());

        String proName = model.getValueAt(selectedRow, 1).toString();
        txtProName.setText(proName);

        String category = model.getValueAt(selectedRow, 2).toString();
        jcbCategory.setSelectedItem(category);

        String type = model.getValueAt(selectedRow, 3).toString();
        if (type.equals("F")) {
            jcbType.setSelectedItem("Fragile");
        } else {
            jcbType.setSelectedItem("Non-Fragile");
        }

        String price = model.getValueAt(selectedRow, 4).toString();
        if (model.getValueAt(selectedRow, 3).equals('F')) {
            double fPrice = Double.parseDouble(price) / 1.1;
            txtPrice.setText(String.valueOf(df.format(fPrice)));
        } else {
            txtPrice.setText(price);
        }

        String stock = model.getValueAt(selectedRow, 5).toString();
        txtQuantity.setText(stock);

    }

    public TableRowSorter<DefaultTableModel> sortTable() {

        DefaultTableModel model = (DefaultTableModel) productTbl.getModel();

        TableRowSorter<DefaultTableModel> sortTable = new TableRowSorter<>(model);
        productTbl.setRowSorter(sortTable);
        return sortTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        ADMIN = new javax.swing.JLabel();
        PANEL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnProduct = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        Rightpanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTbl = new javax.swing.JTable();
        updateProbtn = new javax.swing.JButton();
        deleteProbtn = new javax.swing.JButton();
        txtProName = new javax.swing.JTextField();
        lblProName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        jcbCategory = new javax.swing.JComboBox<>();
        lblType = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox<>();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblProList = new javax.swing.JLabel();
        Roundcorner = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 110, 109));
        Background.setPreferredSize(new java.awt.Dimension(1160, 660));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(255, 110, 109));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADMIN.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ADMIN.setForeground(new java.awt.Color(255, 255, 255));
        ADMIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADMIN.setText("ADMIN");
        LeftPanel.add(ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        PANEL.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        PANEL.setForeground(new java.awt.Color(255, 255, 255));
        PANEL.setText("PANEL");
        LeftPanel.add(PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 110, 109));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(245, 196, 196));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home grey.png"))); // NOI18N
        btnHome.setText(" HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 60));

        jPanel2.setBackground(new java.awt.Color(255, 110, 109));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(245, 196, 196));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer grey.png"))); // NOI18N
        btnCustomer.setText(" CUSTOMER");
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCustomer)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomer)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 60));

        jPanel3.setBackground(new java.awt.Color(255, 110, 109));

        btnProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnProduct.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/product.png"))); // NOI18N
        btnProduct.setText(" PRODUCT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProduct)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 60));

        jPanel4.setBackground(new java.awt.Color(255, 110, 109));

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(245, 196, 196));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order grey.png"))); // NOI18N
        btnOrder.setText("ORDER");
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 60));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sign out.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        LeftPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 40, 50));

        Background.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 660));

        Rightpanel.setBackground(new java.awt.Color(254, 242, 242));
        Rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add grey.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        Rightpanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        Rightpanel.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search black.png"))); // NOI18N
        Rightpanel.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(89, 89, 89));
        jLabel11.setText("Edit Product");
        Rightpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("ADD");
        Rightpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("EDIT");
        Rightpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        Rightpanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 190, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setText("SEARCH");
        Rightpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdmin.setText("HELLO,Admin");
        Rightpanel.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/serach grey.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        Rightpanel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin avatar.png"))); // NOI18N
        Rightpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 50));

        productTbl.setBackground(new java.awt.Color(254, 242, 242));
        productTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Type", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        productTbl.setSelectionBackground(new java.awt.Color(255, 110, 109));
        productTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTbl);
        if (productTbl.getColumnModel().getColumnCount() > 0) {
            productTbl.getColumnModel().getColumn(0).setResizable(false);
            productTbl.getColumnModel().getColumn(0).setPreferredWidth(50);
            productTbl.getColumnModel().getColumn(1).setPreferredWidth(180);
            productTbl.getColumnModel().getColumn(2).setPreferredWidth(100);
            productTbl.getColumnModel().getColumn(3).setResizable(false);
            productTbl.getColumnModel().getColumn(3).setPreferredWidth(50);
            productTbl.getColumnModel().getColumn(4).setResizable(false);
            productTbl.getColumnModel().getColumn(4).setPreferredWidth(80);
            productTbl.getColumnModel().getColumn(5).setResizable(false);
            productTbl.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        Rightpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 520, 340));

        updateProbtn.setBackground(new java.awt.Color(0, 153, 255));
        updateProbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProbtn.setForeground(new java.awt.Color(255, 255, 255));
        updateProbtn.setText("Update");
        updateProbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProbtnActionPerformed(evt);
            }
        });
        Rightpanel.add(updateProbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 90, 40));

        deleteProbtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteProbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteProbtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteProbtn.setText("Delete");
        deleteProbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProbtnActionPerformed(evt);
            }
        });
        Rightpanel.add(deleteProbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 90, 40));
        Rightpanel.add(txtProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, -1));

        lblProName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProName.setText("Product Name");
        Rightpanel.add(lblProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategory.setText("Category");
        Rightpanel.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jcbCategory.setForeground(new java.awt.Color(255, 110, 109));
        jcbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Electronic", "Furnishing", "Fashion" }));
        Rightpanel.add(jcbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        lblType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType.setText("Type");
        Rightpanel.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jcbType.setForeground(new java.awt.Color(255, 110, 109));
        jcbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fragile", "Non-Fragile" }));
        Rightpanel.add(jcbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrice.setText("Selling Price");
        Rightpanel.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        Rightpanel.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 80, -1));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantity.setText("Quantity");
        Rightpanel.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        Rightpanel.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 80, -1));

        lblProList.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblProList.setForeground(new java.awt.Color(89, 89, 89));
        lblProList.setText("Product List");
        Rightpanel.add(lblProList, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        Background.add(Rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 940, 680));

        Roundcorner.setBackground(new java.awt.Color(255, 110, 109));
        Roundcorner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        Roundcorner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 40, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        Roundcorner.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        Background.add(Roundcorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        this.dispose();
        AdminHome m = new AdminHome();
        m.setVisible(true);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        this.dispose();
        AddCustomer m = new AddCustomer();
        m.setVisible(true);
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        this.dispose();
        AddOrder m = new AddOrder();
        m.setVisible(true);
    }//GEN-LAST:event_btnOrderMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Choice", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            this.dispose();
            LoginPage m = new LoginPage();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        this.dispose();
        AddProduct m = new AddProduct();
        m.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        this.dispose();
        ViewProduct m = new ViewProduct();
        m.setVisible(true);
    }//GEN-LAST:event_btnSearchMouseClicked

    private void updateProbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProbtnActionPerformed
        if (txtProName.getText().equals("") || txtPrice.getText().equals("") || txtQuantity.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill in the blank");
            return;
        }
        if (new CustomerManager().isStringNumeric(txtPrice.getText()) || new CustomerManager().isStringNumeric(txtQuantity.getText())) {
            JOptionPane.showMessageDialog(null, "Please insert integer");
            return;
        }
        int row = productTbl.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select row to update");
        } else {
            ProductManager manager = new ProductManager();
            try {
                productList = manager.read();

                int selectedRow = productTbl.convertRowIndexToModel(row);

                productList.get(selectedRow).setProductName(txtProName.getText());
                productList.get(selectedRow).setCategory(jcbCategory.getSelectedItem().toString());
                productList.get(selectedRow).setType(jcbType.getSelectedItem().toString().charAt(0));
                String type = jcbType.getSelectedItem().toString();
                double price = Double.parseDouble(txtPrice.getText());
                if (type.equals("Fragile")) {
                    String fPrice = String.valueOf(df.format(price * 1.1));
                    productList.get(selectedRow).setPrice(Double.parseDouble(fPrice));
                } else {
                    productList.get(selectedRow).setPrice(price);
                }

                productList.get(selectedRow).setStock(Integer.parseInt(txtQuantity.getText()));

                //print to file
                manager.printProList2File(productList);

                JOptionPane.showMessageDialog(this, "Update Successfully");
                addRow2JTable();
                txtProName.setText("");
                jcbCategory.setSelectedIndex(0);
                jcbType.setSelectedIndex(0);
                txtPrice.setText("");
                txtQuantity.setText("");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }

    }//GEN-LAST:event_updateProbtnActionPerformed

    private void deleteProbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProbtnActionPerformed

        ProductManager manager = new ProductManager();
        try {
            int choice = JOptionPane.showConfirmDialog(null, "Are you sure to delete this product?", "Delete", JOptionPane.YES_NO_OPTION);

            if (choice == 0) {
                productList = manager.read();
                int row = productTbl.getSelectedRow();
                int selectedRow = productTbl.convertRowIndexToModel(row);
                ArrayList<Order> orderList = new OrderManager().read();
                for (int i = 0; i < orderList.size(); i++) {
                    for (int j = 0; j < orderList.get(i).orderItems.size(); j++) {
                        if (orderList.get(i).orderItems.get(j).getProduct().getProductID().equals(productList.get(selectedRow).getProductID())) {
                            JOptionPane.showMessageDialog(this, "Products that have been placed by the customer cannot be deleted");
                            return;
                        }

                    }
                }
                ArrayList<Cart> cartList = new CartManager().readcart();
                for (int i = 0; i < cartList.size(); i++) {
                    for (int j = 0; j < cartList.get(i).orderItems.size(); j++) {
                        if (cartList.get(i).orderItems.get(j).getProduct().getProductID().equals(productList.get(selectedRow).getProductID())) {
                            JOptionPane.showMessageDialog(this, "Products that have been placed by the customer cannot be deleted");
                            return;
                        }

                    }
                }
                productList.remove(selectedRow);
                //print to file 
                manager.printProList2File(productList);
                JOptionPane.showMessageDialog(this, "Delete Successfully");
            }
            addRow2JTable();
            txtProName.setText("");
            jcbCategory.setSelectedIndex(0);
            jcbType.setSelectedIndex(0);
            txtPrice.setText("");
            txtQuantity.setText("");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_deleteProbtnActionPerformed

    private void productTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTblMouseClicked

        displayProDetails();

    }//GEN-LAST:event_productTblMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        String searchPro = txtSearch.getText().trim();
        TableRowSorter<DefaultTableModel> search = sortTable();
        productTbl.setRowSorter(search);

        search.setRowFilter(RowFilter.regexFilter("(?i)" + searchPro));
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMIN;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel PANEL;
    private javax.swing.JPanel Rightpanel;
    private javax.swing.JPanel Roundcorner;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnOrder;
    private javax.swing.JLabel btnProduct;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton deleteProbtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JComboBox<String> jcbType;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProList;
    private javax.swing.JLabel lblProName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblType;
    private javax.swing.JTable productTbl;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton updateProbtn;
    // End of variables declaration//GEN-END:variables
}
