/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.CustomerPanel;

import GUI.LoginPage;
import assignment.Customers.Customer;
import assignment.Customers.CustomerManager;
import assignment.Orders.Order;
import assignment.Users.User;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class CustomerOrderItems extends javax.swing.JFrame {

    ArrayList<Order> orderList = new ArrayList<>();
    Order order;
    int RecNo = 0;

    /**
     * Creates new form CustomerOrder
     */
    public CustomerOrderItems() {
        initComponents();
        this.order = order;
        this.setLocationRelativeTo(null);
        try {
            String cusID = new User().readtemp();
            Customer o = new CustomerManager().search(cusID);
            lblusername.setText(o.name.getfName().toUpperCase());
        } catch (IOException ex) {
            System.out.println("Error");
        }
        addRow2OrderJTable();
    }

    public CustomerOrderItems(Order order) {
        initComponents();
        this.order = order;
        this.setLocationRelativeTo(null);
        try {
            String cusID = new User().readtemp();
            Customer o = new CustomerManager().search(cusID);
            lblusername.setText(o.name.getfName().toUpperCase());
        } catch (IOException ex) {
            System.out.println("Error");
        }
        addRow2OrderJTable();
    }

    public void addRow2OrderJTable() {
        DefaultTableModel model = (DefaultTableModel) orderTbl.getModel();

        Object rowData[] = new Object[7];
        model.setRowCount(0);

        for (int i = 0; i < order.orderItems.size(); i++) {
            rowData[0] = order.orderItems.get(i).getProduct().getProductID();
            rowData[1] = order.orderItems.get(i).getProduct().getProductName();
            rowData[2] = order.orderItems.get(i).getProduct().getCategory();
            rowData[3] = order.orderItems.get(i).getProduct().getType();
            rowData[4] = order.orderItems.get(i).getProduct().getPrice();
            rowData[5] = order.orderItems.get(i).getQuantity();
            double total = order.orderItems.get(i).getQuantity() * order.orderItems.get(i).getProduct().getPrice();

            rowData[6] = total;

            model.addRow(rowData);
        };
        lblShowPrice.setText("RM" + String.format("%.2f", order.getTotalPrice()));

        lblShowDate.setText(order.getDate());
        lblShowTime.setText(order.getTime());

    }

    public TableRowSorter<DefaultTableModel> sortOrderTable() {

        DefaultTableModel table = (DefaultTableModel) orderTbl.getModel();

        TableRowSorter<DefaultTableModel> sortOrderTable = new TableRowSorter<>(table);
        orderTbl.setRowSorter(sortOrderTable);
        return sortOrderTable;
    }

    public void showPosDetails(int index) {

        lblShowName.setText(order.orderItems.get(index).getProduct().getProductName());
        lblShowCategory.setText(order.orderItems.get(index).getProduct().getCategory());
        char type = order.orderItems.get(index).getProduct().getType();
        if (type == 'F') {
            lblShowType.setText("Fragile");
        } else {
            lblShowType.setText("Non-Fragile");
        }
        lblShowUnitPrice.setText(String.valueOf(order.orderItems.get(index).getProduct().getPrice()));
        lblShowQuantity.setText(String.valueOf(order.orderItems.get(index).getQuantity()));
        double total = (double) Math.round(order.orderItems.get(index).getProduct().getPrice() * order.orderItems.get(index).getQuantity() * 100) / 100;
        lblShowAmount.setText(String.valueOf(total));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnOrder1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Rightpanel = new javax.swing.JPanel();
        lblOrderItemList = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblShowName = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblAdmin3 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblSearchIcon = new javax.swing.JLabel();
        txtSearchOrder = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        lblTotalPrice = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblAdmin4 = new javax.swing.JLabel();
        lblShowQuantity = new javax.swing.JLabel();
        lblShowTime = new javax.swing.JLabel();
        lblShowPrice = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        lblProName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        btnPrevios = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        lblShowDate = new javax.swing.JLabel();
        lblShowCategory = new javax.swing.JLabel();
        lblShowType = new javax.swing.JLabel();
        lblShowUnitPrice = new javax.swing.JLabel();
        lblShowAmount = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        Roundcorner = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 110, 109));
        Background.setPreferredSize(new java.awt.Dimension(1160, 660));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(255, 110, 109));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 110, 109));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(245, 196, 196));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home grey.png"))); // NOI18N
        btnHome.setText(" HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 60));

        jPanel2.setBackground(new java.awt.Color(255, 110, 109));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(245, 196, 196));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart grey.png"))); // NOI18N
        btnCustomer.setText("  CART");
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnCustomer)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomer)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 60));

        jPanel3.setBackground(new java.awt.Color(255, 110, 109));

        btnOrder1.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOrder1.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order.png"))); // NOI18N
        btnOrder1.setText(" ORDER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder1)
                .addContainerGap())
        );

        LeftPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 60));

        jPanel4.setBackground(new java.awt.Color(255, 110, 109));

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(245, 196, 196));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile grey.png"))); // NOI18N
        btnOrder.setText(" EDIT PROFILE");
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        LeftPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 60));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sign out.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        LeftPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 40, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopvus.png"))); // NOI18N
        LeftPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 80));

        Background.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 660));

        Rightpanel.setBackground(new java.awt.Color(254, 242, 242));
        Rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderItemList.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblOrderItemList.setForeground(new java.awt.Color(89, 89, 89));
        lblOrderItemList.setText("ORDER ITEMS LIST");
        Rightpanel.add(lblOrderItemList, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/myorder.png"))); // NOI18N
        Rightpanel.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 60));

        lblShowName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShowName.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 160, 40));

        lblProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin avatar.png"))); // NOI18N
        Rightpanel.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 50));

        lblAdmin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdmin3.setText("HELLO,");
        Rightpanel.add(lblAdmin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        lblusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusername.setText("customer");
        Rightpanel.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 70, -1));

        lblSearchIcon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search black.png"))); // NOI18N
        Rightpanel.add(lblSearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 30, 30));

        txtSearchOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearchOrder.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtSearchOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchOrderKeyReleased(evt);
            }
        });
        Rightpanel.add(txtSearchOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 460, 50));

        backBtn.setBackground(new java.awt.Color(0, 153, 204));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setMaximumSize(new java.awt.Dimension(167, 29));
        backBtn.setMinimumSize(new java.awt.Dimension(167, 29));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        Rightpanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        orderTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Type", "Price per Unit", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        orderTbl.setRowHeight(40);
        orderTbl.setSelectionBackground(new java.awt.Color(255, 110, 109));
        orderTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(orderTbl);
        if (orderTbl.getColumnModel().getColumnCount() > 0) {
            orderTbl.getColumnModel().getColumn(0).setResizable(false);
            orderTbl.getColumnModel().getColumn(0).setPreferredWidth(60);
            orderTbl.getColumnModel().getColumn(1).setPreferredWidth(120);
            orderTbl.getColumnModel().getColumn(2).setPreferredWidth(120);
            orderTbl.getColumnModel().getColumn(3).setResizable(false);
            orderTbl.getColumnModel().getColumn(3).setPreferredWidth(80);
            orderTbl.getColumnModel().getColumn(4).setResizable(false);
            orderTbl.getColumnModel().getColumn(4).setPreferredWidth(80);
            orderTbl.getColumnModel().getColumn(5).setResizable(false);
            orderTbl.getColumnModel().getColumn(5).setPreferredWidth(60);
            orderTbl.getColumnModel().getColumn(6).setResizable(false);
            orderTbl.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        Rightpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 570, 320));

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTotalPrice.setText("Total Price");
        Rightpanel.add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 120, 40));

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblAdmin.setText("Order Time");
        Rightpanel.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        lblAdmin4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblAdmin4.setText("Order Date");
        Rightpanel.add(lblAdmin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        lblShowQuantity.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShowQuantity.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        lblShowTime.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowTime.setForeground(new java.awt.Color(255, 0, 0));
        lblShowTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowTime.setText("labelTime");
        Rightpanel.add(lblShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 90, -1));

        lblShowPrice.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblShowPrice.setForeground(new java.awt.Color(0, 204, 0));
        lblShowPrice.setText("labelPrice");
        Rightpanel.add(lblShowPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, -1, -1));

        btnFirst.setBackground(new java.awt.Color(255, 102, 102));
        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        Rightpanel.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        lblProName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblProName.setText("Product Name");
        Rightpanel.add(lblProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblCategory.setText("Category");
        Rightpanel.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lblType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblType.setText("Type");
        Rightpanel.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPrice.setText("Price per Unit");
        Rightpanel.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblQuantity.setText("Quantity");
        Rightpanel.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        btnPrevios.setBackground(new java.awt.Color(255, 204, 204));
        btnPrevios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrevios.setForeground(new java.awt.Color(255, 102, 102));
        btnPrevios.setText("<");
        btnPrevios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviosActionPerformed(evt);
            }
        });
        Rightpanel.add(btnPrevios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        btnNext.setBackground(new java.awt.Color(255, 204, 204));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 102, 102));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        Rightpanel.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        btnLast.setBackground(new java.awt.Color(255, 102, 102));
        btnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        Rightpanel.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        lblShowDate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowDate.setForeground(new java.awt.Color(255, 0, 0));
        lblShowDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowDate.setText("labelDate");
        Rightpanel.add(lblShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 110, 90, -1));

        lblShowCategory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShowCategory.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        lblShowType.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShowType.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        lblShowUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShowUnitPrice.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        lblShowAmount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShowAmount.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        lblAmount.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblAmount.setText("Total Amount");
        Rightpanel.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        Background.add(Rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 940, 680));

        Roundcorner.setBackground(new java.awt.Color(255, 110, 109));
        Roundcorner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        Roundcorner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 40, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        Roundcorner.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        Background.add(Roundcorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        this.dispose();
        new CustomerHome().setVisible(true);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        this.dispose();
        new CustomerCart().setVisible(true);
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        this.dispose();
        new CustomerProfile().setVisible(true);
    }//GEN-LAST:event_btnOrderMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Choice", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            this.dispose();
            LoginPage m = new LoginPage();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void txtSearchOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchOrderKeyReleased

        String searchOrder = txtSearchOrder.getText().trim();
        TableRowSorter<DefaultTableModel> search = sortOrderTable();
        orderTbl.setRowSorter(search);

        search.setRowFilter(RowFilter.regexFilter("(?i)" + searchOrder));        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchOrderKeyReleased

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new CustomerOrder().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed

        RecNo = 0;
        showPosDetails(RecNo);

    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviosActionPerformed

        RecNo--; //Record Number
        if (RecNo > 0) {

            showPosDetails(RecNo);

        } else {

            RecNo = 0;
            showPosDetails(RecNo);
        }

    }//GEN-LAST:event_btnPreviosActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        RecNo++;
        if (RecNo < order.orderItems.size()) {

            showPosDetails(RecNo);
        } else {

            RecNo = order.orderItems.size() - 1;
            showPosDetails(RecNo);
            JOptionPane.showMessageDialog(null, "End");

        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        RecNo = order.orderItems.size() - 1; //Record Number
        showPosDetails(RecNo);

    }//GEN-LAST:event_btnLastActionPerformed

    private void orderTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTblMouseClicked

        int selectedRow = orderTbl.convertRowIndexToModel(orderTbl.getSelectedRow());
        showPosDetails(selectedRow);

        // TODO add your handling code here:
    }//GEN-LAST:event_orderTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOrderItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel Rightpanel;
    private javax.swing.JPanel Roundcorner;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JButton btnFirst;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnLast;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel btnOrder;
    private javax.swing.JLabel btnOrder1;
    private javax.swing.JButton btnPrevios;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdmin3;
    private javax.swing.JLabel lblAdmin4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblOrderItemList;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProName;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSearchIcon;
    private javax.swing.JLabel lblShowAmount;
    private javax.swing.JLabel lblShowCategory;
    private javax.swing.JLabel lblShowDate;
    private javax.swing.JLabel lblShowName;
    private javax.swing.JLabel lblShowPrice;
    private javax.swing.JLabel lblShowQuantity;
    private javax.swing.JLabel lblShowTime;
    private javax.swing.JLabel lblShowType;
    private javax.swing.JLabel lblShowUnitPrice;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTable orderTbl;
    private javax.swing.JTextField txtSearchOrder;
    // End of variables declaration//GEN-END:variables
}
