/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminOrder;

import GUI.AdminProduct.AddProduct;
import GUI.AdminCustomer.AddCustomer;
import GUI.AdminHome.AdminHome;
import GUI.LoginPage;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import assignment.Orders.Order;
import assignment.Orders.OrderManager;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class ManageOrder extends javax.swing.JFrame {

    ArrayList<Order> orderList = new ArrayList<>();

    /**
     * Creates new form EditOrder
     */
    public ManageOrder() {
        initComponents();
        this.setLocationRelativeTo(null);
        addOrder2JTable();
        sortOrderTable();
    }

    public void addOrder2JTable() {
        DefaultTableModel model = (DefaultTableModel) orderTbl.getModel();
        try {
            OrderManager oManager = new OrderManager();
            orderList = oManager.read();
            Object rowData[] = new Object[7];
            model.setRowCount(0);
            for (int i = 0; i < orderList.size(); i++) {
                rowData[0] = orderList.get(i).getOrderID();
                rowData[1] = orderList.get(i).getCustomer().getCusID();
                rowData[2] = orderList.get(i).getCustomer().name;
                rowData[3] = orderList.get(i).getDate();
                rowData[4] = orderList.get(i).getTime();
                ArrayList<String> tempArray = new ArrayList<>();
                for (int items = 0; items < orderList.get(i).orderItems.size(); items++) {
                    tempArray.add(orderList.get(i).orderItems.get(items).getProduct().getProductID());
                    tempArray.add(String.valueOf(orderList.get(i).orderItems.get(items).getQuantity()));
                }
                rowData[5] = tempArray;
                rowData[6] = orderList.get(i).getTotalPrice();
                model.addRow(rowData);
            }

        } catch (IOException e) {
            System.out.println("Error");
        }

    }

    public TableRowSorter<DefaultTableModel> sortOrderTable() {

        DefaultTableModel table = (DefaultTableModel) orderTbl.getModel();

        TableRowSorter<DefaultTableModel> sortOrderTable = new TableRowSorter<>(table);
        orderTbl.setRowSorter(sortOrderTable);
        return sortOrderTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        ADMIN = new javax.swing.JLabel();
        PANEL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnProduct = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        Rightpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSearchOrder = new javax.swing.JTextField();
        lblAdmin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        dltOrderbtn = new javax.swing.JButton();
        editOrderbtn1 = new javax.swing.JButton();
        Roundcorner = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 110, 109));
        Background.setPreferredSize(new java.awt.Dimension(1160, 660));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(255, 110, 109));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADMIN.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ADMIN.setForeground(new java.awt.Color(255, 255, 255));
        ADMIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADMIN.setText("ADMIN");
        LeftPanel.add(ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        PANEL.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        PANEL.setForeground(new java.awt.Color(255, 255, 255));
        PANEL.setText("PANEL");
        LeftPanel.add(PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 110, 109));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(245, 196, 196));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home grey.png"))); // NOI18N
        btnHome.setText(" HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 60));

        jPanel2.setBackground(new java.awt.Color(255, 110, 109));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(245, 196, 196));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer grey.png"))); // NOI18N
        btnCustomer.setText(" CUSTOMER");
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCustomer)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomer)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 60));

        jPanel3.setBackground(new java.awt.Color(255, 110, 109));

        btnProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnProduct.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(245, 196, 196));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/product grey.png"))); // NOI18N
        btnProduct.setText(" PRODUCT");
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProduct)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 60));

        jPanel4.setBackground(new java.awt.Color(255, 110, 109));

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order.png"))); // NOI18N
        btnOrder.setText("ORDER");
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 60));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sign out.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        LeftPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 40, 50));

        Background.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 660));

        Rightpanel.setBackground(new java.awt.Color(254, 242, 242));
        Rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search black.png"))); // NOI18N
        Rightpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(89, 89, 89));
        jLabel11.setText("Order History");
        Rightpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtSearchOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearchOrder.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtSearchOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchOrderKeyReleased(evt);
            }
        });
        Rightpanel.add(txtSearchOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 460, 50));

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdmin.setText("HELLO,Admin");
        Rightpanel.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin avatar.png"))); // NOI18N
        Rightpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 50));

        orderTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Customer Name", "Date", "Time", "Ordered Items", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        orderTbl.setRowHeight(40);
        orderTbl.setSelectionBackground(new java.awt.Color(255, 110, 109));
        jScrollPane2.setViewportView(orderTbl);
        if (orderTbl.getColumnModel().getColumnCount() > 0) {
            orderTbl.getColumnModel().getColumn(2).setPreferredWidth(180);
            orderTbl.getColumnModel().getColumn(3).setPreferredWidth(90);
            orderTbl.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        Rightpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 790, 330));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setMaximumSize(new java.awt.Dimension(167, 29));
        backBtn.setMinimumSize(new java.awt.Dimension(167, 29));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        Rightpanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 90, 30));

        dltOrderbtn.setBackground(new java.awt.Color(255, 0, 0));
        dltOrderbtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dltOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        dltOrderbtn.setText("Delete Order");
        dltOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltOrderbtnActionPerformed(evt);
            }
        });
        Rightpanel.add(dltOrderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        editOrderbtn1.setBackground(new java.awt.Color(0, 153, 204));
        editOrderbtn1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        editOrderbtn1.setForeground(new java.awt.Color(255, 255, 255));
        editOrderbtn1.setText("Edit Order");
        editOrderbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrderbtn1ActionPerformed(evt);
            }
        });
        Rightpanel.add(editOrderbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 130, 30));

        Background.add(Rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 940, 680));

        Roundcorner.setBackground(new java.awt.Color(255, 110, 109));
        Roundcorner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        Roundcorner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 40, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        Roundcorner.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        Background.add(Roundcorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        this.dispose();
        AdminHome m = new AdminHome();
        m.setVisible(true);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        this.dispose();
        AddCustomer m = new AddCustomer();
        m.setVisible(true);
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseClicked
        this.dispose();
        AddProduct m = new AddProduct();
        m.setVisible(true);
    }//GEN-LAST:event_btnProductMouseClicked

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        this.dispose();
        AddOrder m = new AddOrder();
        m.setVisible(true);
    }//GEN-LAST:event_btnOrderMouseClicked

    private void txtSearchOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchOrderKeyReleased

        String searchOrder = txtSearchOrder.getText().trim();
        TableRowSorter<DefaultTableModel> search = sortOrderTable();
        orderTbl.setRowSorter(search);

        search.setRowFilter(RowFilter.regexFilter("(?i)" + searchOrder));
    }//GEN-LAST:event_txtSearchOrderKeyReleased

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new AddOrder().setVisible(true);

    }//GEN-LAST:event_backBtnActionPerformed

    private void dltOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltOrderbtnActionPerformed
        try {
            int choice = JOptionPane.showConfirmDialog(null, "Are you sure to delete this order?", "Delete", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                OrderManager oManager = new OrderManager();
                orderList = oManager.read();
                int row = orderTbl.getSelectedRow();
                int selectedRow = orderTbl.convertRowIndexToModel(row); //get the right index after filtering the table
                orderList.remove(selectedRow);
                //print to file
                oManager.printOrder2File(orderList);
                addOrder2JTable();

                //display msg
                JOptionPane.showMessageDialog(this, "Delete Successfully");

            }

        } catch (IOException e) {
        }

    }//GEN-LAST:event_dltOrderbtnActionPerformed

    private void editOrderbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderbtn1ActionPerformed

        int row = orderTbl.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select row to update");
        } else {
            int selectedRow = orderTbl.convertRowIndexToModel(row);
            setVisible(false);
            new AddOrder(selectedRow).setVisible(true);
        }

    }//GEN-LAST:event_editOrderbtn1ActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Choice", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            this.dispose();
            LoginPage m = new LoginPage();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMIN;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel PANEL;
    private javax.swing.JPanel Rightpanel;
    private javax.swing.JPanel Roundcorner;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnOrder;
    private javax.swing.JLabel btnProduct;
    private javax.swing.JButton dltOrderbtn;
    private javax.swing.JButton editOrderbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JTable orderTbl;
    private javax.swing.JTextField txtSearchOrder;
    // End of variables declaration//GEN-END:variables
}
