/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminCustomer;

import GUI.AdminOrder.AddOrder;
import GUI.AdminProduct.AddProduct;
import GUI.AdminHome.AdminHome;
import GUI.LoginPage;
import assignment.Customers.Customer;
import assignment.Customers.CustomerManager;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class ViewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel1
     */
    int RecNo = 0;

    public ViewCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
        addRow2JTable();
        sortTable();
    }

    //print all customer object from arraylist to jtable
    public void addRow2JTable() {
        DefaultTableModel model = (DefaultTableModel) customerTbl.getModel();
        CustomerManager manager = new CustomerManager();
        try {
            ArrayList<Customer> customerList = manager.read();
            Object rowData[] = new Object[6];
            model.setRowCount(0);
            for (int i = 0; i < customerList.size(); i++) {
                rowData[0] = customerList.get(i).getCusID();
                rowData[1] = customerList.get(i).name;
                rowData[2] = customerList.get(i).getGender();
                rowData[3] = customerList.get(i).getPhoneNo();
                rowData[4] = customerList.get(i).getEmail();
                rowData[5] = customerList.get(i).address;
                model.addRow(rowData);

            }

        } catch (IOException e) {
            System.out.println("Error");
        }

    }

    //sort table by columns
    public TableRowSorter<DefaultTableModel> sortTable() {

        DefaultTableModel table = (DefaultTableModel) customerTbl.getModel();

        TableRowSorter<DefaultTableModel> sortTable = new TableRowSorter<DefaultTableModel>(table);
        customerTbl.setRowSorter(sortTable);
        return sortTable;
    }

    // display a particular customer details 
    public void showPosDetails(int index) {
        try {
            ArrayList<Customer> customerList = new CustomerManager().read();
            lblShowName.setText(customerList.get(index).name.getName());

            char gender = customerList.get(index).getGender();
            if (gender == 'F') {
                lblShowGender.setText("Female");

            } else {
                lblShowGender.setText("Male");
            }
            lblShowContact.setText(customerList.get(index).getPhoneNo());
            lblShowEmail.setText(customerList.get(index).getEmail());
            lblShowAddress.setText(customerList.get(index).address.getFullAddress());
        } catch (IOException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        ADMIN = new javax.swing.JLabel();
        PANEL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnProduct = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        Rightpanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTbl = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblContact1 = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnPrevios = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        lblShowEmail = new javax.swing.JLabel();
        lblShowAddress = new javax.swing.JLabel();
        lblShowGender = new javax.swing.JLabel();
        lblShowContact = new javax.swing.JLabel();
        lblShowName = new javax.swing.JLabel();
        Roundcorner = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 110, 109));
        Background.setPreferredSize(new java.awt.Dimension(1160, 660));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(255, 110, 109));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADMIN.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ADMIN.setForeground(new java.awt.Color(255, 255, 255));
        ADMIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADMIN.setText("ADMIN");
        LeftPanel.add(ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        PANEL.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        PANEL.setForeground(new java.awt.Color(255, 255, 255));
        PANEL.setText("PANEL");
        LeftPanel.add(PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 110, 109));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(245, 196, 196));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home grey.png"))); // NOI18N
        btnHome.setText(" HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 60));

        jPanel2.setBackground(new java.awt.Color(255, 110, 109));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N
        btnCustomer.setText(" CUSTOMER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCustomer)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomer)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 60));

        jPanel3.setBackground(new java.awt.Color(255, 110, 109));

        btnProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnProduct.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(245, 196, 196));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/product grey.png"))); // NOI18N
        btnProduct.setText(" PRODUCT");
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProduct)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 60));

        jPanel4.setBackground(new java.awt.Color(255, 110, 109));

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(245, 196, 196));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order grey.png"))); // NOI18N
        btnOrder.setText("ORDER");
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder)
                .addGap(76, 76, 76))
        );

        LeftPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 60));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sign out.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        LeftPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 40, 50));

        Background.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 660));

        Rightpanel.setBackground(new java.awt.Color(254, 242, 242));
        Rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add grey.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        Rightpanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit grey.png"))); // NOI18N
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        Rightpanel.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search black.png"))); // NOI18N
        Rightpanel.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(89, 89, 89));
        jLabel11.setText("Search & View Customer ");
        Rightpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("ADD");
        Rightpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("EDIT");
        Rightpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        Rightpanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setText("SEARCH");
        Rightpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdmin.setText("HELLO,Admin");
        Rightpanel.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        Rightpanel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin avatar.png"))); // NOI18N
        Rightpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 50));

        customerTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Gender", "Contact Number", "E-mail", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        customerTbl.setRowHeight(25);
        customerTbl.setSelectionBackground(new java.awt.Color(255, 110, 109));
        customerTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTbl);
        if (customerTbl.getColumnModel().getColumnCount() > 0) {
            customerTbl.getColumnModel().getColumn(0).setMinWidth(50);
            customerTbl.getColumnModel().getColumn(0).setMaxWidth(50);
            customerTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            customerTbl.getColumnModel().getColumn(2).setMinWidth(50);
            customerTbl.getColumnModel().getColumn(2).setMaxWidth(50);
            customerTbl.getColumnModel().getColumn(3).setPreferredWidth(120);
            customerTbl.getColumnModel().getColumn(4).setPreferredWidth(180);
            customerTbl.getColumnModel().getColumn(5).setPreferredWidth(500);
        }

        Rightpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 890, 270));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Full Name");
        Rightpanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, 30));

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGender.setText("Gender");
        Rightpanel.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 80, 30));

        lblContact1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContact1.setText("Contact Number");
        Rightpanel.add(lblContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 130, 30));

        lblContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContact.setText("Email");
        Rightpanel.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 70, 30));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Address");
        Rightpanel.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, -1));

        btnFirst.setBackground(new java.awt.Color(255, 102, 102));
        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        Rightpanel.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        btnPrevios.setBackground(new java.awt.Color(255, 204, 204));
        btnPrevios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrevios.setForeground(new java.awt.Color(255, 102, 102));
        btnPrevios.setText("<");
        btnPrevios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviosActionPerformed(evt);
            }
        });
        Rightpanel.add(btnPrevios, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        btnNext.setBackground(new java.awt.Color(255, 204, 204));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 102, 102));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        Rightpanel.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        btnLast.setBackground(new java.awt.Color(255, 102, 102));
        btnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        Rightpanel.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, -1, -1));

        lblShowEmail.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowEmail.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 200, 50));

        lblShowAddress.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowAddress.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 530, -1));

        lblShowGender.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowGender.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 70, 30));

        lblShowContact.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowContact.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 120, 30));

        lblShowName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblShowName.setForeground(new java.awt.Color(255, 110, 109));
        Rightpanel.add(lblShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 140, -1));

        Background.add(Rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 940, 680));

        Roundcorner.setBackground(new java.awt.Color(255, 110, 109));
        Roundcorner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        Roundcorner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 40, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/round corner.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        Roundcorner.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        Background.add(Roundcorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 660));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Choice", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            this.dispose();
            LoginPage m = new LoginPage();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        this.dispose();
        AddCustomer m = new AddCustomer();
        m.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        this.dispose();
        EditCustomer m = new EditCustomer();
        m.setVisible(true);
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        this.dispose();
        AdminHome m = new AdminHome();
        m.setVisible(true);

    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseClicked
        this.dispose();
        AddProduct m = new AddProduct();
        m.setVisible(true);
    }//GEN-LAST:event_btnProductMouseClicked

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        this.dispose();
        AddOrder m = new AddOrder();
        m.setVisible(true);
    }//GEN-LAST:event_btnOrderMouseClicked

    private void customerTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTblMouseClicked

        int selectedRow = customerTbl.convertRowIndexToModel(customerTbl.getSelectedRow());
        showPosDetails(selectedRow);

    }//GEN-LAST:event_customerTblMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String searchCus = txtSearch.getText().trim();
        TableRowSorter<DefaultTableModel> search = sortTable();
        customerTbl.setRowSorter(search);

        search.setRowFilter(RowFilter.regexFilter("(?i)" + searchCus)); //ignore case sentitive       
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed

        RecNo = 0;//Record Number
        showPosDetails(RecNo);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviosActionPerformed

        RecNo--;
        if (RecNo > 0) {

            showPosDetails(RecNo);

        } else {

            RecNo = 0;
            showPosDetails(RecNo);
        }
    }//GEN-LAST:event_btnPreviosActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            ArrayList<Customer> customerList = new CustomerManager().read();
            RecNo++;
            if (RecNo < customerList.size()) {

                showPosDetails(RecNo);
            } else {

                RecNo = customerList.size() - 1;
                showPosDetails(RecNo);
                JOptionPane.showMessageDialog(null, "End");

            }
        } catch (IOException e) {
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed

        try {
            ArrayList<Customer> customerList = new CustomerManager().read();
            RecNo = customerList.size() - 1; //Record Number
            showPosDetails(RecNo);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_btnLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMIN;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel PANEL;
    private javax.swing.JPanel Rightpanel;
    private javax.swing.JPanel Roundcorner;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnLast;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel btnOrder;
    private javax.swing.JButton btnPrevios;
    private javax.swing.JLabel btnProduct;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JTable customerTbl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContact1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblShowAddress;
    private javax.swing.JLabel lblShowContact;
    private javax.swing.JLabel lblShowEmail;
    private javax.swing.JLabel lblShowGender;
    private javax.swing.JLabel lblShowName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
